#!/bin/bash -x
#PBS -l select=1:ncpus=16:model=san_gpu
#PBS -q k40
#PBS -l walltime=1:00:00
#PBS -j oe
#PBS -N Conv-GPUrun

cd $PBS_O_WORKDIR

# set up
source /usr/local/lib/init/global.cshrc
module purge

# Use NAS miniconda
source /u/analytix/tools/opt/miniconda3/etc/profile.d/conda.csh
module load comp-intel/2018.3.222

# Use NAS tools
source activate tf_9_gpu_k40

# command to run:
python3 test.py

source deactivate
#end of script
