#!/bin/bash
set -euxo pipefail
# -e exit on first error
# -u exit if variable is not set
# -x print each command run to stdout
# -o pipefail return the error status of the last command to exit

pip-compile --no-index requirements.in requirements-dev.in -o requirements.txt
