#!/bin/bash
set -euxo pipefail
# -e exit on first error
# -u exit if variable is not set
# -x print each command run to stdout
# -o pipefail return the error status of the last command to exit

echo "Checking code style with pylint..."
python3 -m pylint wildfire
echo "Success!"

echo "Checking code style with pydocstyle..."
python3 -m pydocstyle wildfire
echo "Success!"

echo "Running unit and integration tests..."
python -m pytest -v tests/
echo "Success!"
