#!/bin/bash
set -euxo pipefail
# -e exit on first error
# -u exit if variable is not set
# -x print each command run to stdout
# -o pipefail return the error status of the last command to exit


./scripts/test

echo "Running integration tests..."
python -m pytest -v tests/it
echo "Success!"
